name: hello_flutter
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  url_launcher: ^6.0.5
  http: 0.13.3
  flutter_webview_plugin: 0.4.0
  date_format: 2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/lake.jpg
    - images/pic.jpg
    - images/pavlova.jpg
    - images/pic01.jpg
    - images/pic02.jpg
    - images/pic03.jpg
    - images/pic04.jpg
    - images/pic1.jpg
    - images/pic2.jpg
    - images/pic3.jpg
    - images/pic4.jpg
    - images/pic5.jpg
    - images/pic6.jpg
    - images/pic7.jpg
    - images/pic8.jpg
    - images/pic9.jpg
    - images/pic10.jpg
    - images/pic11.jpg
    - images/pic12.jpg
    - images/pic13.jpg
    - images/pic14.jpg
    - images/pic15.jpg
    - images/pic16.jpg
    - images/pic17.jpg
    - images/pic18.jpg
    - images/pic19.jpg
    - images/pic20.jpg
    - images/pic21.jpg
    - images/pic22.jpg
    - images/pic23.jpg
    - images/pic24.jpg
    - images/pic25.jpg
    - images/pic26.jpg
    - images/pic27.jpg
    - images/pic28.jpg
    - images/pic29.jpg
    - images/pic30.jpg
    - images/beachball-alpha.png
    - images/binoculars-alpha.png
    - images/chair-alpha.png
    - images/flippers-alpha.png
    - images/contact_list_normal.png
    - images/contact_list_pressed.png
    - images/icon_addfriend.png
    - images/icon_groupchat.png
    - images/icon_me_clear.png
    - images/icon_me_file.png
    - images/icon_me_friends.png
    - images/icon_me_message.png
    - images/icon_me_photo.png
    - images/icon_me_service.png
    - images/icon_menu_addfriend.png
    - images/icon_menu_scan.png
    - images/icon_menu_group.png
    - images/icon_public.png
    - images/loading.jpeg
    - images/message_normal.png
    - images/message_pressed.png
    - images/profile_normal.png
    - images/profile_pressed.png
    - images/yixiu.jpeg

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
